language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 20iALz3KBJfj2VTOAVnK7DJ9dJzDcjPDzw3WJqa2n9532Z4uabVONPxtXR+NB+rPnssGIV/433uDAzsVk96ODXwt1f7nUT1/tM/eUraQYNO/o8eZuidQAk2C+Sxf8o73ADmZlyQEVj/Gc5mstMbXyEAc7CxWE9epI9EEhuGLp5Afr7SvLZCrYO3rQqeG5ogulvcdWV+tgGkO5Goh7PfqE8n3ZfvRf1iMffxRptNcZoyl4sGxvMfX+oKNWcDTdSgx/Al5g79EApg6MXNnKA7FXkk0XlQF8w4mETzip8WQh5nlja4ddRoPO0NZHUSpzQyKg7aW514Pskw9/HcWS5nq8UjvPdI9Ct1//9Lwl/2KGWyB9NY2mReoFDL80aG2OnSxzEx4Pp3dTZ24C44u+0QWRpY0gctLUWSZ3J/qfJTEZhpmUHkz8pJmExiCoa7vgmA5vhNIgI7n1+4cZ4zio/TxkT/o3T9cycj8ENNTQ0r0Sas2khCXgJcFfS2MYwBiPSjWBU8G9WtdCp4Si5eH9r0tRkojeu/pIF8atUyDkpsod1F9u4d/6CuSdHAECPZ2h+M3DO0H7A8r59/QeyMDzFY04iK88LNwXUYWRrwcVzGU5mnc1cuR0eoljybwxwp8W1bnWiMKS8KkuFWgqYds5eiTek0c17WWDdM4t7osif+Hgpw=
  file:
    - "rehype-retext.js"
    - "rehype-retext.min.js"
  on:
    tags: true
