language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HxdKAg7T5RLeEAnqoIcftGbk+aof2V44h3/vBBaemTDR0MTIEqZDBDp/U2r1enPTNI/EEggdxZZTGN9RO5JlBA/aOMaiif8sUH0d7dVodjzlW30Hr/UbCqFb54lp6ONd6bc+EghdrtJlL4wl+lcJOVmP9F6BUVZsnOJaxhb2nWuPH6m4Hg7DRlfVbsJ2Ga1Gzp2cH1lZfueWuxRDWEJuqanybDDdQ/GJk+TAVllUaew21NIrjpPoRm12icL9JrZGb+fNpmNGE9BMs4S6ITh+HQ941n1qHu5rbPJtUho/rDkK76Rkb3fdiIxjJwzf1qG5cLdmWE4v3kaH/ZIJS1JrpVlf7bTIQn5o2Ol7vPV3R6h6A46CpYAn794/AatYxYlhtGKz6Lx5stedmylgYXK6m+aseMvntxS+q1t81OTZifabcXaTJjFOEYYGGaPrVoTqFceuj0p6MoLQt1lykzpCEmdTcDwLLn3G6YfQ+580MdrkktMpfD8Vwph8iItItk24c0L3bCBO9fpDRjnM+wyJJGLzWKdoDydtwg842sEsPaHLPEWxpuWIpbcy4pvNvhLstLt+r+P4vxVI4pjvFFb/BJnLBC3Rlxh7/K176NJw9a49kjkEmtHgWzVpri0NVtkjx1K6+tJbbc9F9iBP3WsK9z2kBF7ICWcwRLlVjO8uMm8=
  file:
    - "rehype-retext.js"
    - "rehype-retext.min.js"
  on:
    tags: true
